// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIRV6qLmIOOerssqWi5JlGEls6ssSIQfk',
    appId: '1:824955819624:web:675f5eb35f6e4e713dcddd',
    messagingSenderId: '824955819624',
    projectId: 'my-p-8a0a0',
    authDomain: 'my-p-8a0a0.firebaseapp.com',
    storageBucket: 'my-p-8a0a0.firebasestorage.app',
    measurementId: 'G-LZGFVCSTKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtXRmhcg3EBVvXeHndq3Yp635Z3eljxRQ',
    appId: '1:824955819624:android:9611c7869a4d3c033dcddd',
    messagingSenderId: '824955819624',
    projectId: 'my-p-8a0a0',
    storageBucket: 'my-p-8a0a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8cB4nCb_C9fsYh_oYYGqfRSMCm9jvE8',
    appId: '1:824955819624:ios:ece28dd01743eb493dcddd',
    messagingSenderId: '824955819624',
    projectId: 'my-p-8a0a0',
    storageBucket: 'my-p-8a0a0.firebasestorage.app',
    iosBundleId: 'com.example.one',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs8cB4nCb_C9fsYh_oYYGqfRSMCm9jvE8',
    appId: '1:824955819624:ios:ece28dd01743eb493dcddd',
    messagingSenderId: '824955819624',
    projectId: 'my-p-8a0a0',
    storageBucket: 'my-p-8a0a0.firebasestorage.app',
    iosBundleId: 'com.example.one',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIRV6qLmIOOerssqWi5JlGEls6ssSIQfk',
    appId: '1:824955819624:web:27ba0d090f8c48ac3dcddd',
    messagingSenderId: '824955819624',
    projectId: 'my-p-8a0a0',
    authDomain: 'my-p-8a0a0.firebaseapp.com',
    storageBucket: 'my-p-8a0a0.firebasestorage.app',
    measurementId: 'G-LH5G0LQPT4',
  );
}
